version: "3"
volumes:
  logs.app:
  cache.app:
services:
  nginx:
    container_name: nginx.catalog
    build:
      context: ./
      dockerfile: Dockerfile_NGINX
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./local:/local
      - logs.app:/app/var/logs
      - cache.app:/app/var/cache
      - ./host.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php.catalog
    build:
      context: ./
      dockerfile: Dockerfile_PHP
    volumes:
      - ./local:/local
      - logs.app:/app/var/logs
      - cache.app:/app/var/cache
